// styles.ts
import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#5D3FD3",
    position: "relative",
  },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    overflow: "hidden",
  },
  headerBlur: {
    flex: 1,
    justifyContent: "flex-end",
    padding: 16,
  },
  headerContent: {
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFD700",
    fontFamily: Platform.OS === "ios" ? "Marker Felt" : "normal",
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 3,
    textAlign: "center",
  },
  headerSubtitle: {
    fontSize: 16,
    color: "#FFD700",
    marginTop: 5,
    fontWeight: "500",
  },
  emoji: {
    fontSize: 48,
    marginBottom: 5,
  },
  premiumBadge: {
    backgroundColor: "#FFD700",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    position: "absolute",
    top: 10,
    right: 10,
    transform: [{ rotate: "3deg" }],
  },
  premiumText: {
    color: "#5D3FD3",
    fontWeight: "bold",
    fontSize: 12,
  },
  scrollContainer: {
    padding: 16,
    paddingTop: 180, // Account for header height
  },
  // Add these styles to your existing styles object
  reviewedBadge: {
    backgroundColor: "#4CAF50", // Green color for the badge
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  reviewedText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
  },
  backButton: {
    position: "absolute",
    top: 50,
    left: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFD700",
    justifyContent: "center",
    alignItems: "center",
    transform: [{ rotate: "-5deg" }],
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
    zIndex: 1000,
  },
  backButtonText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#5D3FD3",
  },
  card: {
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    transform: [{ rotate: "-0.5deg" }],
  },
  cardHeader: {
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#5D3FD3",
    marginBottom: 4,
  },
  divider: {
    height: 3,
    width: 40,
    backgroundColor: "#FFD700",
    borderRadius: 2,
  },
  ratingSection: {
    alignItems: "center",
    marginBottom: 16,
  },
  ratingLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#5D3FD3",
    marginBottom: 4,
  },
  detailedRatings: {
    marginTop: 16,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  ratingCategory: {
    width: 80,
    fontSize: 14,
    color: "#444",
  },
  ratingBar: {
    flex: 1,
    height: 8,
    backgroundColor: "rgba(93, 63, 211, 0.1)",
    borderRadius: 4,
    marginHorizontal: 10,
    overflow: "hidden",
  },
  ratingFill: {
    height: "100%",
    backgroundColor: "#FFD700",
    borderRadius: 4,
  },
  ratingValue: {
    width: 30,
    fontSize: 14,
    fontWeight: "bold",
    color: "#5D3FD3",
    textAlign: "right",
  },
  reviewCountContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  viewReviewsButton: {
    marginLeft: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "rgba(93, 63, 211, 0.1)",
    borderRadius: 12,
  },
  viewReviewsText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#5D3FD3",
  },
  reviewCount: {
    fontSize: 14,
    color: "#666",
    fontStyle: "italic",
  },
  infoRow: {
    flexDirection: "row",
    marginBottom: 12,
    alignItems: "flex-start",
  },
  infoLabel: {
    width: 80,
    fontSize: 14,
    fontWeight: "bold",
    color: "#5D3FD3",
  },
  infoValue: {
    flex: 1,
    fontSize: 14,
    color: "#333",
  },
  codeRow: {
    flexDirection: "row",
    marginBottom: 16,
    justifyContent: "center",
  },
  codeLabel: {
    width: 145,
    fontSize: 18,
    fontWeight: "bold",
    color: "#5D3FD3",
  },
  codeValue: {
    flex: 1,
    fontSize: 18,
    color: "#333",
    fontWeight: "bold",
  },
  description: {
    fontSize: 15,
    color: "#444",
    lineHeight: 22,
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 0,
    marginBottom: 12,
  },
  actionButton: {
    width: "48%",
    borderRadius: 30,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  primaryButton: {
    backgroundColor: "#FFD700",
    transform: [{ rotate: "-1deg" }],
  },
  primaryButtonText: {
    color: "#5D3FD3",
    fontWeight: "bold",
    fontSize: 16,
  },
  secondaryButton: {
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderWidth: 2,
    borderColor: "#FFD700",
    transform: [{ rotate: "1deg" }],
  },
  secondaryButtonText: {
    color: "#5D3FD3",
    fontWeight: "bold",
    fontSize: 16,
  },
  decorationCircle1: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(255, 215, 0, 0.15)",
    top: -80,
    right: -50,
    zIndex: -1,
  },
  decorationCircle2: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(255, 255, 208, 0.2)",
    bottom: 100,
    left: -40,
    zIndex: -1,
  },
  decorationCircle3: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(255, 215, 0, 0.1)",
    bottom: -30,
    right: -30,
    zIndex: -1,
  },
  seeMoreButton: {
    alignItems: "center",
    paddingVertical: 10,
    marginTop: 5,
  },
  seeMoreText: {
    color: "#5D3FD3",
    fontWeight: "500",
    fontSize: 14,
  },
  featuresGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  featureBadge: {
    width: "30%",
    backgroundColor: "rgba(93, 63, 211, 0.1)",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(93, 63, 211, 0.2)",
  },
  featureIcon: {
    fontSize: 22,
    marginBottom: 5,
  },
  featureLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "#5D3FD3",
    textAlign: "center",
  },
});
